package com.zara.assistant.core

/**
 * Layer 5.7 — Immutable execution contract.
 * Generated by ExecutionGuard before ActionExecutor runs.
 */
data class ExecutionContract(
    val safe: Boolean,
    val retryable: Boolean,
    val action: String,
    val app: String,
    val target: String? = null,
    val query: String? = null,
    val fallbackAction: String? = null
)
